### ISSUE TITLE
[V3] Imgflip errors when passing 3 text values for a meme with 3 text fields

### ISSUE THREAD

**Issue by Mystard** [TrustyJAID/Trusty-cogs-archive#10]
Some imgflip memes, like "Distracted Boyfriend" have 3 text fields, but passing 4 arguments (meme name + 3 texts) doesn't work with the cog.

`[p]meme Distracted Boyfriend;test1;test2`
returns an image with just the 2 texts filled

`[p]meme Distracted Boyfriend;test1;test2;test3`
results in an error:

```
Exception in command 'meme'
Traceback (most recent call last):
  File "/home/red3/.local/lib/python3.5/site-packages/discord/ext/commands/core.py", line 62, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/red3/Red-DiscordBot3/cogs/CogManager/cogs/imgflip/imgflip.py", line 65, in meme
    text1 = text1[:20] if len(text1) > 20 else text1
UnboundLocalError: local variable 'text1' referenced before assignment

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/red3/.local/lib/python3.5/site-packages/discord/ext/commands/bot.py", line 886, in invoke
    yield from ctx.command.invoke(ctx)
  File "/home/red3/.local/lib/python3.5/site-packages/discord/ext/commands/core.py", line 514, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "/home/red3/.local/lib/python3.5/site-packages/discord/ext/commands/core.py", line 71, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: UnboundLocalError: local variable 'text1' referenced before assignment
```

Debian 8 Jessie, Red - Version 3.0.0b14, Python 3.5.3+

**Comment by TrustyJAID** [comment]
I just committed a fix to warn you for using more than 2 text entries. The API for Imgflip does not allow for more than 2 entries for text unfortunately.
