### ISSUE TITLE
i cant set set modlog channel

### ISSUE THREAD

**Issue by AHIRAISSHY** [TrustyJAID/Trusty-cogs-archive#27]
What i did here:

``?modlogset modlog #general``

the error that gave me:
```py
Exception in command 'modlogset modlog'
Traceback (most recent call last):
  File "C:\Users\Angel\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\ext\commands\core.py", line 61, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\Angel\AppData\Local\Programs\Python\Python37-32\lib\site-packages\redbot\cogs\modlog\modlog.py", line 37, in modlog
    await modlog.set_modlog_channel(guild, channel)
  File "C:\Users\Angel\AppData\Local\Programs\Python\Python37-32\lib\site-packages\redbot\core\modlog.py", line 717, in set_modlog_channel
    await _conf.guild(guild).mod_log.set(channel.id if hasattr(channel, "id") else None)
  File "C:\Users\Angel\AppData\Local\Programs\Python\Python37-32\lib\site-packages\redbot\core\config.py", line 153, in set
    await self.driver.set(*self.identifiers, value=value)
  File "C:\Users\Angel\AppData\Local\Programs\Python\Python37-32\lib\site-packages\redbot\core\drivers\red_json.py", line 112, in set
    await self.jsonIO._threadsafe_save_json(self.data)
  File "C:\Users\Angel\AppData\Local\Programs\Python\Python37-32\lib\site-packages\redbot\core\json_io.py", line 74, in _threadsafe_save_json
    await loop.run_in_executor(None, func)
  File "C:\Users\Angel\AppData\Local\Programs\Python\Python37-32\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Angel\AppData\Local\Programs\Python\Python37-32\lib\site-packages\redbot\core\json_io.py", line 53, in _save_json
    with tmp_path.open(encoding="utf-8", mode="w") as f:
  File "C:\Users\Angel\AppData\Local\Programs\Python\Python37-32\lib\pathlib.py", line 1165, in open
    opener=self._opener)
  File "C:\Users\Angel\AppData\Local\Programs\Python\Python37-32\lib\pathlib.py", line 1019, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Angel\\AppData\\Local\\Red-DiscordBot\\Red-DiscordBot\\cogs\\ModLog\\settings-3957949200.tmp'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Angel\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\ext\commands\bot.py", line 898, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\Angel\AppData\Local\Programs\Python\Python37-32\lib\site-packages\redbot\core\commands\commands.py", line 409, in invoke
    await super().invoke(ctx)
  File "C:\Users\Angel\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\ext\commands\core.py", line 1024, in invoke
    await ctx.invoked_subcommand.invoke(ctx)
  File "C:\Users\Angel\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\ext\commands\core.py", line 614, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\Angel\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\ext\commands\core.py", line 70, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Angel\\AppData\\Local\\Red-DiscordBot\\Red-DiscordBot\\cogs\\ModLog\\settings-3957949200.tmp'
```

**Comment by AHIRAISSHY** [comment]
it doesnt work in python 3.7 or idk
