### ISSUE TITLE
[V3] Starboard manual starring error ([p]star command)

### ISSUE THREAD

**Issue by Mystard** [TrustyJAID/Trusty-cogs-archive#9]
Trying to star messages with `[p]star <message id>` doesn't work and gives an error.

```
Exception in command 'star'
Traceback (most recent call last):
  File "/home/red3/.local/lib/python3.5/site-packages/discord/ext/commands/core.py", line 62, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/red3/Red-DiscordBot3/cogs/CogManager/cogs/starboard/starboard.py", line 76, in star
    post_msg = await channel2.send("{} **#{}**".format(emoji, count), embed=em)
NameError: name 'count' is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/red3/.local/lib/python3.5/site-packages/discord/ext/commands/bot.py", line 886, in invoke
    yield from ctx.command.invoke(ctx)
  File "/home/red3/.local/lib/python3.5/site-packages/discord/ext/commands/core.py", line 514, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "/home/red3/.local/lib/python3.5/site-packages/discord/ext/commands/core.py", line 71, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: NameError: name 'count' is not defined
```

Debian 8 Jessie, Red - Version 3.0.0b14, Python 3.5.3+

`[p]star` is also missing the help information and doesn't return anything when doing either `[p]star` or `[p]help star`

**Comment by TrustyJAID** [comment]
Fixed in [d61556b](https://github.com/TrustyJAID/Trusty-cogs/commit/d61556b719b358d49c88ca472cae0ea96e77625f) and [c6842f0](https://github.com/TrustyJAID/Trusty-cogs/commit/c6842f078cea52e3fb700ceb1af17abce10d0b03).
